default: &default
  adapter: postgresql
  host: postgres # такой же, как имя сервиса бд в docker-compose.yml
  user: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: books_development

test:
  <<: *default
  database: books_test

production:
  <<: *default
  host: books-postgres # from /kube/postgres-service.yml
  database: <%= ENV['POSTGRES_DB'] %>
  user: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
