# A Kubernetes deployment manifest for Postgres would look similar to the example.
# Create a single pod replica. Use a base image postgres:11.5. Expose port 5432.
# Environment variables set using parameters found in a ConfigMap.
# Mount a Persistent Volume using a Persistent Volume Claim for the Postgres database files.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-postgres
  template:
    metadata:
      labels:
        app: control-postgres
    spec:
      containers:
        - name: control-postgres
          image: postgres:11.5
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: control-postgres-config
          volumeMounts:
            - name: controldb
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: controldb
          persistentVolumeClaim:
            claimName: control-postgres-pv-claim
