apiVersion: v1
kind: Service
metadata:
  name: library
  labels:
    name: library
spec:
  type: LoadBalancer
  loadBalancerIP: 35.205.133.66 # use external IP here (gcloud compute addresses list)
  ports:
    - port: 80
      targetPort: 8280
      protocol: TCP
  selector:
    name: library # exposes all containers matching the name=library selector behind this load balancer
