apiVersion: apps/v1
kind: Deployment
metadata:
  name: library
  labels:
    name: library
spec:
  replicas: 2
  selector:
    matchLabels:
      name: library
  template:
    metadata:
      labels:
        name: library
    spec:
      nodeSelector:
        # indicate that this pod has an affinity for the default-pool node pool,
        # so it doesn't get scheduled on our db-pool nodes which are reserved
        # for our postgres pod
        cloud.google.com/gke-nodepool: default-pool
      containers:
        - name: library
          image: PROJECT/LIBRARY_IMAGE # a placeholder value, will be replaced by Kustomize tool
          ports:
            - containerPort: 8280
          livenessProbe:
            httpGet:
              path: /_health
              port: 8280
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /_health
              port: 8280
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 1
          envFrom:
            - configMapRef:
                name: library-postgres-config
          env:
          - name: RAILS_MASTER_KEY
            valueFrom:
              secretKeyRef:
                name: library-secrets
                key: rails-master-key
          env:
          - name: RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secrets
                key: username
          env:
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secrets
                key: password
