# A Kubernetes deployment manifest for Postgres would look similar to the example.
# Create a single pod replica. Use a base image postgres:11.5. Expose port 5432.
# Environment variables set using parameters found in a ConfigMap.
# Mount a Persistent Volume using a Persistent Volume Claim for the Postgres database files.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-postgres
  template:
    metadata:
      labels:
        app: library-postgres
    spec:
      containers:
        - name: library-postgres
          image: postgres:11.5
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: library-postgres-config # from postgres-configmap.yml
          volumeMounts:
            - name: librarydb
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: librarydb
          persistentVolumeClaim:
            claimName: library-postgres-pv-claim #from postgres-storage.yml
