version: '3'
services:
  postgres:
    image: postgres:11.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  books:
    build: ./books-service
    volumes:
      - .:/usr/src
    working_dir: /usr/src/books-service
    ports:
      - 8180:8180
    depends_on:
      - postgres

  library:
    build: ./library-service
    volumes:
      - .:/usr/src
    working_dir: /usr/src/library-service
    ports:
      - 8280:8280
    depends_on:
      - postgres

  control:
    build: ./control-service
    volumes:
      - .:/usr/src
    working_dir: /usr/src/control-service
    ports:
      - 8380:8380
    depends_on:
      - postgres

  rating:
    build: ./rating-service
    volumes:
      - .:/usr/src
    working_dir: /usr/src/rating-service
    ports:
      - 8480:8480
    depends_on:
      - postgres

  gateway:
    build: ./gateway-service
    volumes:
      - .:/usr/src
    working_dir: /usr/src/gateway-service
    ports:
      - 8580:8580

  session:
    build: ./session-service
    volumes:
      - .:/usr/src
    working_dir: /usr/src/session-service
    ports:
      - 8680:8680
    depends_on:
      - postgres

  report:
    build: ./report-service
    volumes:
      - .:/usr/src
    working_dir: /usr/src/report-service
    ports:
      - 8780:8780

  frontend:
    build: ./frontend
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    working_dir: /usr/src/frontend
    ports:
      - 8980:8980

volumes:
  postgres:
