apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    name: gateway
spec:
  type: LoadBalancer
  loadBalancerIP: 34.76.150.43
  ports:
    - port: 80
      targetPort: 8580
      protocol: TCP
  selector:
    name: gateway
