apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    name: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      name: gateway
  template:
    metadata:
      labels:
        name: gateway
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
        - name: gateway
          image: us.gcr.io/book-sea/gateway@sha256:0e6ebe6e2d54d5f4822b12db5cadb0ab52c116cfc3624946a666ce72208bdc28
          ports:
            - containerPort: 8580
          livenessProbe:
            httpGet:
              path: /_health
              port: 8580
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /_health
              port: 8580
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 1
