apiVersion: v1
kind: Service
metadata:
  name: report
  labels:
    name: report
spec:
  type: LoadBalancer
  loadBalancerIP: 34.76.185.153
  ports:
    - port: 80
      targetPort: 8780
      protocol: TCP
  selector:
    name: report
