apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  selector:
    matchLabels:
      name: frontend
  replicas: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        name: frontend
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
        - name: frontend
          image: PROJECT/FRONTEND_IMAGE
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
          imagePullPolicy: Always
